### ISSUE TITLE
CLB Productions for TABConf

### ISSUE THREAD

**Issue by JoseMoranUrena523** [TABConf/2023.tabconf.com#7]
Hey, I am the owner of CLB Productions and I would like to be a speaker at TABConf. I can’t like physically go anywhere, but if there is anything I can do, let me know. I am the owner/developer of 2048 Bitcoin (as featured in a blog by ZEBEDEE which you can see [here](https://blog.zebedee.io/hobby-developers-feat-2048) which you guys can play by clicking [here](https://2048bitcoin.world/) and you can also see the new company website by clicking [over here](https://clbproductions.games/).

**Comment by iglesiasbrandon** [comment]
Hey @JoseMoranUrena523, thank you for submitting an issue! I spent some time playing 2048 Bitcoin and got sucked into it haha. it's a great integration with ZEBEDEE, nice work! Since this issue does not mention a specific topic you would like to speak about or give a workshop on I am going to close it. Please open another Github issue if you have a specific topic!
