### ISSUE TITLE
Running a LND Routing Node - Liquidity Management & Tools for Automation

### ISSUE THREAD

**Issue by Bitcoinite** [TABConf/2023.tabconf.com#8]
# Description
## What is this workshop about? Provide as many details as possible.
This workshop is aiming at attendees that are planning to, or are already running a LND routing node, and want to learn how to manage a routing node of significant size and traffic. It will be open to active discussion throughout the whole workshop. LNDg will be used during the workshop to help visualize the concepts we will be discussing.

### The workshop will consist of three subjects:

1) Liquidity Management (Fees):
The first subject of the workshop will focus on fee management. I will explain how to evaluate what fees you need to set to your individual peers. This includes evaluating whether a peer is acting as a source/sink/router from your nodes point of view. Knowing this enables you to set proper fees that will prevent your liquidity from draining to the remote side too fast as well as prevent liquidity from being stuck locally. Running a routing node is about providing liquidity to the network wherever it is requested. Setting up and managing fees is a major part of providing this service.
2) Liquidity Management (Rebalancing):
After explaining fee strategies, the second part will focus on rebalancing channels. As we are running a liquidity service, we need to make sure, that the liquidity we are providing, is always available in the channels, where it is requested by the other participants in the network. Since demand for liquidity is higher on some routes, a routing node has to make sure, that these routes don't run out of liquidity. We therefore need to have a detailed look on how to actively rebalance lightning channels.
3) Automation Tools:
In the final part of the workshop, I will introduce the attendees to features of LNDg, a valuable tool to automate the things we've learned about liquidity management. These features include using the rebalancer, setting up auto-fees, tracking node metrics and more if time allows.
What would an attendee learn from this workshop?
How to set up and mange proper fee rates depending on liquidity flow
How to set up auto rebalancing for different kinds of peers (sources, sinks, routers)
An overview of LNDg and it's most important functions
Is there anything attendees should read up on before they attend this talk?
Not required.

### Is there anything attendees should set up before the workshop?
- If you are running a LND routing node, you might want to set up and get a brief overview of [LNDg](https://github.com/cryptosharks131/lndg) prior to the workshop. This will give you an opportunity to ask some questions during the workshop.

### Relevant Links
- [LNDg](https://github.com/cryptosharks131/lndg)

## About the Speaker
Social Links
Github: https://github.com/cryptosharks131
Twitter: [@cryptosharks131](https://twitter.com/cryptosharks131)

**Comment by iglesiasbrandon** [comment]
Hey @Bitcoinite, Thank you for submitting a workshop issue for TABConf 2023! You are among the first to submit! As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule: https://github.com/orgs/TABConf/projects/1.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions about your issue. (thank you for providing such a detailed description!)

**Comment by Bitcoinite** [comment]
I need to close this issue since I can't make it to the conference unfortunately.

**Comment by iglesiasbrandon** [comment]
Hey @Bitcoinite, I'm sorry to hear that; thank you for opening the issue in the first place. We hope you can make it to the next one! 

I think this is a very relevant topic, so one thing we could do is reopen the issue and add the looking for speakers label in case someone else is interested in speaking on this topic. 

Let me know your thoughts on this idea.

**Comment by cryptosharks131** [comment]
I am planning to attend the conference this year and would love to help with this workshop if there is still sufficient interest!

**Comment by miketwenty1** [comment]
Would @cryptosharks131  be the host of this workshop then if accepted?
cc @Bitcoinite

**Comment by cryptosharks131** [comment]
I can host the workshop and focus on the topics @Bitcoinite had planned.

**Comment by iglesiasbrandon** [comment]
Hey @cryptosharks131 that sounds great; thank you! This issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The workshops will be happening on September 6th and 7th; once we accept some more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment]
Hey @Bitcoinite , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/4

Please acknowledge by commenting 'ack'.

This will confirm your workshop for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by Bitcoinite** [comment]
This should be done by @cryptosharks131 since I cannot attend the conf and he will host the workshop

**Comment by iglesiasbrandon** [comment]
> Please acknowledge by commenting 'ack'.

oh yea sorry about that! @Bitcoinite

**Comment by cryptosharks131** [comment]
ack

**Comment by miketwenty1** [comment]
@cryptosharks131

I'm sending this to all accepted upcoming workshop. Please review and ensure you have a clear, up to date, high level, agenda on this GitHub issue. Please buffer in time to help with unexpected problems and questions.

TABConf workshops should aim to involve high levels participation. If you're planning to conduct a live demo, please consider that attendees will require clear instructions on how to prepare for following along, (all steps for setup should be double checked) and any presentation should be structured accordingly.
Participants should leave the workshop either with something built, (be it physical or digital), or with specific knowledge gained from the __hands on/interactive__ experience.

**Comment by cryptosharks131** [comment]
# Description
### What is this workshop about? Provide as many details as possible. 

This workshop is aiming at attendees that are planning to, or are already running a LND routing node, and want to learn how to manage a routing node of significant size and traffic. It will be open to active discussion throughout the whole workshop. LNDg will be used during the workshop to help visualize the concepts we will be discussing.

The workshop will consist of three subjects:

1. Liquidity Management (Fees):
The first subject of the workshop will focus on fee management. I will explain how to evaluate what fees you need to set to your individual peers. This includes evaluating whether a peer is acting as a source/sink/router from your nodes point of view. Knowing this enables you to set proper fees that will prevent your liquidity from draining to the remote side too fast as well as prevent liquidity from being stuck locally. Running a routing node is about providing liquidity to the network wherever it is requested. Setting up and managing fees is a major part of providing this service.
2. Liquidity Management (Rebalancing):
After explaining fee strategies, the second part will focus on rebalancing channels. As we are running a liquidity service, we need to make sure, that the liquidity we are providing, is always available in the channels, where it is requested by the other participants in the network. Since demand for liquidity is higher on some routes, a routing node has to make sure, that these routes don't run out of liquidity. We therefore need to have a detailed look on how to actively rebalance lightning channels.
3. Automation Tools:
In the final part of the workshop, I will introduce the attendees to features of LNDg, a valuable tool to automate the things we've learned about liquidity management. These features include using the rebalancer, setting up auto-fees, tracking node metrics and more if time allows.

### What would an attendee learn from this workshop?

- How to set up and mange proper fee rates depending on liquidity flow
- How to set up auto rebalancing for different kinds of peers (sources, sinks, routers)
- An overview of LNDg and it's most important functions

### Is there anything attendees should read up on before they attend this talk?

Not required.

### Is there anything attendees should set up before the workshop?

If you are running a LND routing node, you might want to set up and get a brief overview of [LNDg](https://github.com/cryptosharks131/lndg) prior to the workshop.  This will give you an opportunity to ask some questions during the workshop.

### Relevant Links
[LNDg](https://github.com/cryptosharks131/lndg)

# About the Speaker
### Social Links
Github: https://github.com/cryptosharks131
Twitter: [@cryptosharks131](https://twitter.com/cryptosharks131)

**Comment by iglesiasbrandon** [comment]
Hey @cryptosharks131 i updated the first comment "description" of the issue with what you posted above. thank you!

**Comment by iglesiasbrandon** [comment]
Hey @cryptosharks131 , I am closing this issue since you have completed the workshop. Thank you for all of the effort you put into it!
